### ISSUE TITLE
Does sideRETRO work for non-human samples?

### ISSUE THREAD

**Issue by tbenavi1** [galantelab/sideRETRO#7]
Hello,

I was wondering if it is possible to use sideRETRO on non-human samples. When I run sideRetro on my samples, I get the following warning: "WARN  merge_call.c:239: No cluster has been found!" I'm not sure if sideRETRO is assuming that the chromosome names will be human chromosome names. The produced database file is about 1GB in size, but the out.vcf file is completely empty. Of course, there may be some other issue. Thanks for any assistance.

**Comment by thiago-miller** [comment]
Hello, @tbenavi1 - sorry for the delayed answer.

We have not tested sideRETRO with non-human samples, however we assume that it is possible to use the tool with those types of data. The warning message you received says there are not enough sequence reads inside a given genome locus in order to cluster it and then annotate it as a new retrocopy event - that is why the VCF file is empty.

As you pointed out, there may be some other issue, for example: The sequencing read length, the transcriptome annotation (GTF, GFF3), the aligner used (bwa align, bwa mem) and more.

Please, send me an e-mail with more information, such as: The animal specie, the annotation file (GTF or GFF3), the sequencing type (illumina, read length, coverage), the aligner (it is very important).

I will be glad to help!

My email: <tmiller@mochsl.org.br>

Best regards,
Thiago L. A. Miller
